export const VENDOR_CSS = [
  "/assets/vendors/bootstrap/css/bootstrap.min.css",
  "/assets/vendors/animate/animate.min.css",
  "/assets/vendors/animate/custom-animate.css",
  "/assets/vendors/fontawesome/css/all.min.css",
  "/assets/vendors/jarallax/jarallax.css",
  "/assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css",
  "/assets/vendors/nouislider/nouislider.min.css",
  "/assets/vendors/nouislider/nouislider.pips.css",
  "/assets/vendors/odometer/odometer.min.css",
  "/assets/vendors/swiper/swiper.min.css",
  "/assets/vendors/oslim-icons/style.css",
  "/assets/vendors/tiny-slider/tiny-slider.min.css",
  "/assets/vendors/reey-font/stylesheet.css",
  "/assets/vendors/owl-carousel/owl.carousel.min.css",
  "/assets/vendors/owl-carousel/owl.theme.default.min.css",
  "/assets/vendors/bxslider/jquery.bxslider.css",
  "/assets/vendors/bootstrap-select/css/bootstrap-select.min.css",
  "/assets/vendors/vegas/vegas.min.css",
  "/assets/vendors/jquery-ui/jquery-ui.css",
  "/assets/vendors/timepicker/timePicker.css",
  "/assets/css/oslim.css",
  "/assets/css/oslim-responsive.css",
];

// Order matters: each entry depends on the ones before it (jQuery first,
// oslim.js last). Loaded via next/script strategy="afterInteractive" so they
// run only after React finishes hydrating — running them earlier caused
// hydration mismatches when they mutated nav DOM nodes React had just hydrated.
export const VENDOR_JS = [
  "/assets/vendors/jquery/jquery-3.6.0.min.js",
  "/assets/vendors/bootstrap/js/bootstrap.bundle.min.js",
  "/assets/vendors/jarallax/jarallax.min.js",
  "/assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js",
  "/assets/vendors/jquery-appear/jquery.appear.min.js",
  "/assets/vendors/jquery-circle-progress/jquery.circle-progress.min.js",
  "/assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js",
  "/assets/vendors/jquery-validate/jquery.validate.min.js",
  "/assets/vendors/nouislider/nouislider.min.js",
  "/assets/vendors/odometer/odometer.min.js",
  "/assets/vendors/swiper/swiper.min.js",
  "/assets/vendors/tiny-slider/tiny-slider.min.js",
  "/assets/vendors/wnumb/wNumb.min.js",
  "/assets/vendors/wow/wow.js",
  "/assets/vendors/isotope/isotope.js",
  "/assets/vendors/countdown/countdown.min.js",
  "/assets/vendors/owl-carousel/owl.carousel.min.js",
  "/assets/vendors/bxslider/jquery.bxslider.min.js",
  "/assets/vendors/bootstrap-select/js/bootstrap-select.min.js",
  "/assets/vendors/vegas/vegas.min.js",
  "/assets/vendors/jquery-ui/jquery-ui.js",
  "/assets/vendors/timepicker/timePicker.js",
  "/assets/js/oslim.js",
];
